---
- name: check nginx status on target machine
  hosts: managednode1
  gather_facts: false
  tasks:
    - name: check nginx service status
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_status
      ignore_errors: true

    - name: print nginx status
      debug:
        var: nginx_status.stdout
        verbosity: 1

    - name: Save nginx status to file
      ansible.builtin.copy:
        content: "{{ nginx_status.stdout }}\n"
        dest: /tmp/nginx_status.txt

    - name: list files from user home directory
      ansible.builtin.find:
        paths: /home/githuba
        file_type: any
      register: home_files
      ignore_errors: true

    - name: print home directory files list
      debug:
        msg: "{{ item.path }}"
        verbosity: 1
      loop: "{{ home_files.files }}"

    - name: save this outout as CSV file
      ansible.builtin.copy:
        content: |
          {% for file in home_files.files %}
          {{ file.path }}
          {% endfor %}
        dest: /tmp/home_files.csv
  
    